export const phaseLabels: Record<string, string> = {
    checking: "Comprobando...",
    downloading: "Descargando...",
    downloading_signature: "Verificando firma...",
    verifying: "Verificando integridad...",
    extracting: "Extrayendo...",
    installing_deps: "Instalando dependencias...",
    compiling: "Compilando...",
    done: "Instalado",
    already_installed: "Ya estaba instalado",
    linked: "Vinculado al proyecto",
    unlinked: "Desvinculado",
    uninstalled: "Desinstalado",
    synced: "Sincronizado",
    not_found: "No encontrado",
    not_installed: "No instalado",
    not_linked: "No estaba en uso",
    error: "Error",
};
